import { useEffect, useRef, useState } from "react"; import { useNavigate } from "react-router-dom";
import { CameraStage } from "../components/CameraStage"; import { primaryTip } from "../lib/postureRules"; import { saveReport } from "../lib/localResults"; import type { PostureItem, Status } from "../types/detection";
const empty: Record<PostureItem, Status> = { head:"unknown", torso:"unknown", shoulders:"unknown", lean:"unknown" };
export function PosturePage() { const nav=useNavigate(); const [ready,setReady]=useState(false); const [running,setRunning]=useState(false); const [usable,setUsable]=useState(false); const [left,setLeft]=useState(10); const samples=useRef<Record<PostureItem,Status>[]>([]); const result=useRef(empty);
  useEffect(()=>{ if(!running||!usable) return; if(left<=0){ setRunning(false); const items=(Object.keys(empty) as PostureItem[]).reduce((a,k)=>{ const all=samples.current.map(s=>s[k]); a[k]=all.filter(x=>x==="adjust").length >= Math.max(3,all.length*.35) ? "adjust" : all.length ? "good" : "unknown"; return a; },{...empty}); result.current=items; saveReport({id:crypto.randomUUID(),createdAt:new Date().toISOString(),durationSeconds:10,items,primaryTip:primaryTip(items),modelVersion:"MediaPipe Pose Lite"}); nav("/report"); return; } const id=window.setTimeout(()=>setLeft(v=>v-1),1000); return()=>clearTimeout(id); },[running,usable,left,nav]);
  if(!ready) return <main className="app-shell guide"><button className="back" onClick={()=>nav(-1)}>‹</button><h1>坐姿检测</h1><p className="subtitle">先帮孩子摆好一个舒服的位置</p><div className="guide-art">⌁<span>头部、双肩、上半身<br/>和桌面都进入画面</span></div><ol><li>手机放在书桌前侧约 45°</li><li>让画面看到头部、双肩和书本</li><li>准备好后再打开摄像头</li></ol><button className="btn primary big" onClick={()=>setReady(true)}>我已摆好，打开摄像头</button></main>;
  return <main className="app-shell detector"><header className="page-head"><button className="back" onClick={()=>nav(-1)}>‹</button><h1>坐姿检测</h1><span>?</span></header><div className="lion-tip">🦁　{usable ? "坐得很稳，继续保持！" : "请让头部和两侧肩膀进入画面"}</div><CameraStage kind="pose" onPose={({usable,items})=>{setUsable(usable); if(running&&usable) samples.current.push(items);}}/>
  <p className="camera-note">取景时请露出头部、肩膀与桌面</p>{!running?<button className="btn primary big" disabled={!usable} onClick={()=>{samples.current=[];setLeft(10);setRunning(true)}}>{usable?"开始 10 秒检测":"等待画面准备好"}</button>:<div className="timer"><div><b>{left}</b><span>秒</span></div></div>}<p className="bottom-message">{running?"检测中，请保持姿势……":"视频仅在本机实时分析"}</p></main>;
}
